### ISSUE TITLE
delete_atoms command with ID issues

### ISSUE THREAD

**Issue by claireb5112** [mrkllntschpp/lammps-tutorials#3]
Hello,
Thanks for all these great tutorials! I got stuck with the delete_atoms command. I am looking at the LAMMPS documentation and comparing codes and I can't see where I am going wrong, yet I continue to get the error "ERROR: Could not find delete_atoms group ID (../delete_atoms.cpp:306)
Last command: delete_atoms overlap 0.35 region lower upper" 
I get this error right after it starts the displacing atoms section. I copied my code directly from your code posted on this tutorial, so I am confused with what is happening.

**Comment by mrkllntschpp** [comment]
Thanks for pointing this out.  All these scripts have worked for me, and I don't see anything in my scripts.  I just reran Tutorial 5 and had no problems.  If it is another tutorial, please identify which tutorial so I can take a look.  I would check to make sure that the create_atoms commands and the group commands are inserted in your script--the error is telling you that either those are not there or the group name doesn't exist.

**Comment by claireb5112** [comment]
Yeah, it was just tutorial 5 that I was having issues using the delete_atoms code. Thank you so much!!!!
