### ISSUE TITLE
is:issue is:open files not reading 

### ISSUE THREAD

**Issue by sydshap** [mrkllntschpp/lammps-tutorials#4]
after opening the correct folder in the terminal and running the code, lmp_serial -in in.lmp, the file is not opening. is there a specific way the files should be organized so that lammps is able to read it or is there another issue here. 
<img width="414" alt="Screen Shot 2020-05-28 at 10 16 13 AM" src="https://user-images.githubusercontent.com/66075315/83152857-4931e280-a0cc-11ea-9c12-c9ded98ffa45.png">

**Comment by mrkllntschpp** [comment]
The screen shot of the directory doesn't help too much.  Are you seeing an error message after you run?  What does it say?  That usually helps to troubleshoot.  There is a input script, a potential script, and in some cases, a datafile with atom coordinates/velocities.  LAMMPS may not be finding one of those.  A common problem is that the name in the input script doesn't match the one in the folder, or that the file isn't in the folder that LAMMPS thinks it is in.  Last, hopefully permissions isn't blocking it from accessing for some reason.  Best of luck!  I just ran and it works for me.
